src/ContosoUniversity/Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ContosoUniversity.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/ContosoUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Logan Minor</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>




<body id="mainBody">

    <div id="navigationBar" class="navbar navbar-inverse navbar-fixed-left">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <ul class="nav navbar-nav">
                <li data-toggle="tooltip" data-placement="right" title="Home"><a asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home"></span></a></li>
                <li data-toggle="tooltip" data-placement="right" title="Favorite Authors"><a asp-controller="Authors" asp-action="Index"><span class="glyphicon glyphicon-book"></span></a></li>
                <li data-toggle="tooltip" data-placement="right" title="Games"><a asp-controller="Games" asp-action="Index"><span class="glyphicon glyphicon-knight"></span></a></li>
                <li data-toggle="tooltip" data-placement="right" title="Interactive Resume"><a asp-controller="Resume" asp-action="Index"><span class="glyphicon glyphicon-duplicate"></span></a></li>
                <li style="left: 0px;"><span>@await Html.PartialAsync("_LoginPartial")</span></li>
            </ul>
        </div>
    </div>

    @RenderSection("Tweet", required: false)
    @RenderSection("gameRibbon", required: false)
    @RenderSection("socialMedia", required: false)
    <div class="container body-content" style="background-color: #e6e6e6;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Logan Minor</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>